name: npm-package-cd
on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js >=v16
        uses: actions/setup-node@v3
        with:
          node-version: '>=16'
          cache: 'pnpm'
      - run: |
          pnpm i
          pnpm build
      - run: pnpm publish -r --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}