name: publish publish-vscode-extension-fe-integration

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js >=v16
        uses: actions/setup-node@v3
        with:
          node-version: ">=16"
          cache: "pnpm"
      - run: |
          pnpm i
          pnpm build
      - name: Publish
        if: success()
        run: npm run deploy -C vscodeExtension/fe-integration
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
