name: 发布npm包

on:
  workflow_dispatch:

permissions: write-all

env:
  npm_org: \@utilslib

jobs:
  checkPackageVersion:
    outputs:
      corePublish: ${{ steps.compare-version.outputs.corePublish }}
      domPublish: ${{ steps.compare-version.outputs.domPublish }}
      vue2Publish: ${{ steps.compare-version.outputs.vue2Publish }}
      vue3Publish: ${{ steps.compare-version.outputs.vue3Publish }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js >=v16
        uses: actions/setup-node@v3
        with:
          node-version: ">=16"

      - name: Install jq
        run: sudo apt update && sudo apt install -y jq

      - name: Get current package.json version
        id: get-current-version
        run: |
          core_current_version=$(cat packages/core/package.json | jq -r .version)
          echo "core_current_version=$core_current_version" >> $GITHUB_OUTPUT
          echo "core_current_version=$core_current_version"

          dom_current_version=$(cat packages/dom/package.json | jq -r .version)
          echo "dom_current_version=$dom_current_version" >> $GITHUB_OUTPUT
          echo "dom_current_version=$dom_current_version"

          vue2_current_version=$(cat packages/vue2/package.json | jq -r .version)
          echo "vue2_current_version=$vue2_current_version" >> $GITHUB_OUTPUT
          echo "vue2_current_version=$vue2_current_version"

          vue3_current_version=$(cat packages/vue3/package.json | jq -r .version)
          echo "vue3_current_version=$vue3_current_version" >> $GITHUB_OUTPUT
          echo "vue3_current_version=$vue3_current_version"

      - name: Get npm latest version
        id: get-npm-version
        run: |
          if core_latest_version=$(npm view ${{ env.npm_org }}/core version 2>/dev/null); then
            echo "get core Package version: $core_latest_version"
          else
            echo "Failed to get core package version, setting to -1"
            core_latest_version="-1"
          fi

          echo "core_latest_version=$core_latest_version" >> $GITHUB_OUTPUT
          echo "core_latest_version=$core_latest_version"

          if dom_latest_version=$(npm view ${{ env.npm_org }}/dom version 2>/dev/null); then
            echo "get core Package version: $dom_latest_version"
          else
            echo "Failed to get dom package version, setting to -1"
            dom_latest_version="-1"
          fi
          echo "dom_latest_version=$dom_latest_version" >> $GITHUB_OUTPUT
          echo "dom_latest_version=$dom_latest_version"

          if vue2_latest_version=$(npm view ${{ env.npm_org }}/vue2 version 2>/dev/null); then
            echo "get core Package version: $vue2_latest_version"
          else
            echo "Failed to get vue2 package version, setting to -1"
            vue2_latest_version="-1"
          fi
          echo "vue2_latest_version=$vue2_latest_version" >> $GITHUB_OUTPUT
          echo "vue2_latest_version=$vue2_latest_version"

          if vue3_latest_version=$(npm view ${{ env.npm_org }}/vue3 version 2>/dev/null); then
            echo "get core Package version: $vue3_latest_version"
          else
            echo "Failed to get vue3 package version, setting to -1"
            vue3_latest_version="-1"
          fi
          echo "vue3_latest_version=$vue3_latest_version" >> $GITHUB_OUTPUT
          echo "vue3_latest_version=$vue3_latest_version"

      - name: Compare versions
        id: compare-version
        run: |
          core_current_version=${{ steps.get-current-version.outputs.core_current_version }}
          core_latest_version=${{ steps.get-npm-version.outputs.core_latest_version }}

          dom_current_version=${{ steps.get-current-version.outputs.dom_current_version }}
          dom_latest_version=${{ steps.get-npm-version.outputs.dom_latest_version }}

          vue2_current_version=${{ steps.get-current-version.outputs.vue2_current_version }}
          vue2_latest_version=${{ steps.get-npm-version.outputs.vue2_latest_version }}

          vue3_current_version=${{ steps.get-current-version.outputs.vue3_current_version }}
          vue3_latest_version=${{ steps.get-npm-version.outputs.vue3_latest_version }}

          if [ "$core_current_version" != "$core_latest_version" ]; then
            echo "${{ env.npm_org }}/core Version has changed. Triggering the build."
            echo "corePublish=1" >> $GITHUB_OUTPUT
          else
            echo "core version has not changed. Skipping the build."
          fi

          if [ "$dom_current_version" != "$dom_latest_version" ]; then
            echo "${{ env.npm_org }}/dom Version has changed. Triggering the build."
            echo "domPublish=1" >> $GITHUB_OUTPUT
          else
            echo "dom version has not changed. Skipping the build."
          fi

          if [ "$vue2_current_version" != "$vue2_latest_version" ]; then
            echo "${{ env.npm_org }}/dom Version has changed. Triggering the build."
            echo "vue2Publish=1" >> $GITHUB_OUTPUT
          else
            echo "vue2 version has not changed. Skipping the build."
          fi

          if [ "$vue3_current_version" != "$vue3_latest_version" ]; then
            echo "${{ env.npm_org }}/dom Version has changed. Triggering the build."
            echo "vue3Publish=1" >> $GITHUB_OUTPUT
          else
            echo "vue3 version has not changed. Skipping the build."
          fi

      - name: Build and test
        if: steps.compare-version.outputs.trigger_build == 'true'
        run: |
          # 在这里执行构建和测试操作
          echo "Building and testing..."

  publish:
    runs-on: ubuntu-latest
    needs: checkPackageVersion
    if: needs.checkPackageVersion.outputs.corePublish == 1 || needs.checkPackageVersion.outputs.domPublish == 1 || needs.checkPackageVersion.outputs.vue2Publish == 1 || needs.checkPackageVersion.outputs.vue3Publish == 1
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js >=v16
        uses: actions/setup-node@v3
        with:
          node-version: ">=16"
          cache: "pnpm"
      - run: |
          pnpm i
          pnpm build

      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Deploy core to npm
        id: core_publish
        if: needs.checkPackageVersion.outputs.corePublish == 1
        run: pnpm --filter ${{ env.npm_org }}/core  publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Deploy dom to npm
        id: dom_publish
        if: needs.checkPackageVersion.outputs.domPublish == 1
        run: pnpm --filter ${{ env.npm_org }}/dom  publish --no-git-checks --access public

      - name: Deploy vue2 to npm
        id: vue2_publish
        if: needs.checkPackageVersion.outputs.vue2Publish == 1
        run: pnpm --filter ${{ env.npm_org }}/vue2  publish --no-git-checks --access public

      - name: Deploy vue3 to npm
        id: vue3_publish
        if: needs.checkPackageVersion.outputs.vue3Publish == 1
        run: pnpm --filter ${{ env.npm_org }}/vue3  publish --no-git-checks --access public

  trigger:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: 触发fe-integration vsce发布更新
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.SECRETS_TOKEN }}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${{ github.repository_owner }}/fe-integration/actions/workflows/triggerVersionUpgrade.yml/dispatches" -d '{"ref":"main"}'

      - name: 触发utilslib 文档更新
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/doc.yml/dispatches" -d '{"ref":"main"}'
