name: publish npm

on:
  workflow_dispatch:

env:
  npm_org: \@utilslib

jobs:
  checkPackageVersion:
    outputs:
      corePublish: ${{ steps.compare-version.outputs.corePublish }}
      domPublish: ${{ steps.compare-version.outputs.domPublish }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js >=v16
        uses: actions/setup-node@v3
        with:
          node-version: ">=16"

      - name: Install jq
        run: sudo apt update && sudo apt install -y jq

      - name: Get current package.json version
        id: get-current-version
        run: |
          core_current_version=$(cat packages/core/package.json | jq -r .version)
          echo "core_current_version=$core_current_version" >> $GITHUB_OUTPUT
          echo "core_current_version=$core_current_version"

          dom_current_version=$(cat packages/dom/package.json | jq -r .version)
          echo "dom_current_version=$dom_current_version" >> $GITHUB_OUTPUT
          echo "dom_current_version=$dom_current_version"

      - name: Get npm latest version
        id: get-npm-version
        run: |
          if core_latest_version=$(npm view ${{ env.npm_org }}/core version 2>/dev/null); then
            echo "get core Package version: $core_latest_version"
          else
            echo "Failed to get core package version, setting to -1"
            core_latest_version="-1"
          fi

          echo "core_latest_version=$core_latest_version" >> $GITHUB_OUTPUT
          echo "core_latest_version=$core_latest_version"

          if dom_latest_version=$(npm view ${{ env.npm_org }}/dom version 2>/dev/null); then
            echo "get core Package version: $dom_latest_version"
          else
            echo "Failed to get dom package version, setting to -1"
            dom_latest_version="-1"
          fi
          echo "dom_latest_version=$dom_latest_version" >> $GITHUB_OUTPUT
          echo "dom_latest_version=$dom_latest_version"

      - name: Compare versions
        id: compare-version
        run: |
          core_current_version=${{ steps.get-current-version.outputs.core_current_version }}
          core_latest_version=${{ steps.get-npm-version.outputs.core_latest_version }}

          dom_current_version=${{ steps.get-current-version.outputs.dom_current_version }}
          dom_latest_version=${{ steps.get-npm-version.outputs.dom_latest_version }}


          if [ "$core_current_version" != "$core_latest_version" ]; then
            echo "${{ env.npm_org }}/core Version has changed. Triggering the build."
            echo "corePublish=1" >> $GITHUB_OUTPUT
          else
            echo "core version has not changed. Skipping the build."
          fi

          if [ "$dom_current_version" != "$dom_latest_version" ]; then
            echo "${{ env.npm_org }}/dom Version has changed. Triggering the build."
            echo "domPublish=1" >> $GITHUB_OUTPUT
          else
            echo "dom version has not changed. Skipping the build."
          fi

      - name: Build and test
        if: steps.compare-version.outputs.trigger_build == 'true'
        run: |
          # 在这里执行构建和测试操作
          echo "Building and testing..."

  build:
    runs-on: ubuntu-latest
    needs: checkPackageVersion
    if: needs.checkPackageVersion.outputs.corePublish == 1 || needs.checkPackageVersion.outputs.domPublish == 1
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js >=v16
        uses: actions/setup-node@v3
        with:
          node-version: ">=16"
          cache: "pnpm"
      - run: |
          pnpm i
          pnpm build

      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Deploy core to npm
        id: core_publish
        if: needs.checkPackageVersion.outputs.corePublish == 1
        run: pnpm --filter ${{ env.npm_org }}/core  publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Deploy dom to npm
        id: dom_publish
        if: needs.checkPackageVersion.outputs.domPublish == 1
        run: pnpm --filter ${{ env.npm_org }}/dom  publish --no-git-checks --access public

  push:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Git
        run: |
          git config --global user.name 'Tuan'
          git config --global user.email 'ibin@qq.com'
      - name: Upgrade
        run: |
          cd vscodeExtension/fe-integration
          npm version patch

      - name: Commit and push
        run: |
          git add .
          git commit -m "feat: fe-integration patch"
          git push

  trigger:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Trigger doc workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/doc.yml/dispatches" -d '{"ref":"main"}'

      - name: Trigger doc vscode-extension workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/publish-vscode-extension-fe-integration.yml/dispatches" -d '{"ref":"main"}'
