name: publish publish-vscode-extension-fe-integration

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt update && sudo apt install -y jq
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js >=v16
        uses: actions/setup-node@v3
        with:
          node-version: ">=16"
          cache: "pnpm"
      - run: |
          pnpm i
          pnpm build
      - name: Publish
        if: success()
        run: |
          cd vscodeExtension/fe-integration
          PUBLISHED=$(pnpm vsce search Jiabin.fe-integration --json | jq -r '.[].versions[0].version')
          CURRENT=$(cat package.json | jq -r '.version')
          if [ "$PUBLISHED" != "$CURRENT" ]; then
            npm run deploy
          fi
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
