name: test

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Git
        run: |
          git config --global user.name 'Tuan'
          git config --global user.email 'ibin@qq.com'
      - name: Upgrade
        run: |
          git pull --rebase
          cd vscodeExtension/fe-integration
          npm version patch

      - name: Commit
        run: |
          git add .
          git commit -m "feat: fe-integration patch"
          git push

  trigger:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Trigger doc workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/doc.yml/dispatches" -d '{"ref":"main"}'

      - name: Trigger doc vscode-extension workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/publish-vscode-extension-fe-integration.yml/dispatches" -d '{"ref":"main"}'
