name: test

on:
  workflow_dispatch:

permissions: write-all

env:
  npm_org: \@utilslib

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Trigger doc workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${{ github.repository_owner }}/fe-integration/actions/workflows/triggerVersionUpgrade.yml/dispatches" -d '{"ref":"main"}'
