name: CI on Package.json Version Change

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Get previous commit's package.json version
      id: get-previous-version
      run: |
        previous_commit=$(git log -n 1 --skip=2 --pretty=format:%H -- package.json)
        previous_version=$(git show $previous_commit:package.json | jq -r .version)
        echo "previous_version=$previous_version" >> $GITHUB_OUTPUT
        echo "previous_version=$previous_version"


    - name: Get current package.json version
      id: get-current-version
      run: |
        current_version=$(cat package.json | jq -r .version)
        echo "current_version=$current_version" >> $GITHUB_OUTPUT
        echo "current_version=$current_version"

    - name: Compare versions
      id: compare-version
      run: |
        previous_version=${{ steps.get-previous-version.outputs.previous_version }}
        current_version=${{ steps.get-current-version.outputs.current_version }}
        if [ "$previous_version" != "$current_version" ]; then
          echo "Version has changed. Triggering the build."
          echo "::set-output name=trigger_build::true"
        else
          echo "Version has not changed. Skipping the build."
        fi

    - name: Build and test
      if: steps.compare-version.outputs.trigger_build == 'true'
      run: |
        # 在这里执行构建和测试操作
        echo "Building and testing..."
